@SharpAgent.API_HostAddress = http://localhost:5291

GET {{SharpAgent.API_HostAddress}}/weatherforecast/
Accept: application/json

###


### Send a basic chat completion request
POST {{SharpAgent.API_HostAddress}}/api/chatcompletion/sendchatcompletion
Content-Type: application/json

        {
            "role": "user",
            "content": "How many alieans have visited Earth so far?"
        }


### Extract paragraphs from a PDF document
POST {{SharpAgent.API_HostAddress}}/api/documentanalysis/extractparagraphs
Content-Type: application/json

{
    "documentUrl": "https://www.uky.edu/ccd/sites/www.uky.edu.ccd/files/pawpaw.pdf"
}


### Create Embeddings
POST {{SharpAgent.API_HostAddress}}/api/embeddings/create
Content-Type: application/json

{
    "textSections": [
        "This is the first section to embed",
        "This is another section that needs embedding",
        "And here's a third section for good measure"
    ]
}