using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Text;

using SharpAgent.Application.IServices;
using SharpAgent.Domain.Models;

namespace SharpAgent.Infrastructure.Services;

public class TranscriptService : ITranscriptService
{
    private readonly HttpClient _httpClient;
    private readonly ILogger<TranscriptService> _logger;
    private readonly string _tokenId;

    public TranscriptService(
        IConfiguration configuration,
        ILogger<TranscriptService> logger)
    {
        if (configuration == null)
            throw new ArgumentNullException(nameof(configuration));

        _logger = logger ?? throw new ArgumentNullException(nameof(logger));

        _tokenId = configuration["Apify:TokenId"]
            ?? throw new InvalidOperationException("Apify:TokenId configuration is missing");

        _httpClient = new HttpClient();
        _httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", _tokenId);
    }

    public async Task<TranscriptResult> ScrapeVideoAsync(string videoUrl)
    {
        try
        {
            _logger.LogInformation($"Scraping YouTube video: {videoUrl}");

            // Prepare the request payload
            var requestPayload = new
            {
                downloadSubtitles = true,
                preferAutoGeneratedSubtitles = true,
                subtitlesLanguage = "en",
                startUrls = new[]
                {
                new
                {
                    url = videoUrl,
                    method = "GET"
                }
            }
            };

            var content = new StringContent(
                JsonConvert.SerializeObject(requestPayload),
                Encoding.UTF8,
                "application/json");

            var runRequest = new HttpRequestMessage(HttpMethod.Post, "https://api.apify.com/v2/acts/streamers~youtube-scraper/runs");
            runRequest.Content = content;

            var runResponse = await _httpClient.SendAsync(runRequest);
            _logger.LogInformation($"Initial Apify response: {runResponse.StatusCode}");

            if (!runResponse.IsSuccessStatusCode)
            {
                _logger.LogWarning($"Failed to start scraping job: {runResponse.StatusCode}");
                return null;
            }

            // Get the run ID from the response
            var runResponseContent = await runResponse.Content.ReadAsStringAsync();
            _logger.LogInformation($"Run response: {runResponseContent}");

            var runData = JsonConvert.DeserializeObject<ApifyRunResponse>(runResponseContent);

            if (runData?.Data?.Id == null)
            {
                _logger.LogWarning("Failed to get run ID from Apify response");
                return null;
            }

            string runId = runData.Data.Id;
            _logger.LogInformation($"Started Apify run with ID: {runId}");

            // Poll for the run status
            return await WaitForRunCompletion(runId, videoUrl);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, $"Error scraping YouTube video {videoUrl}: {ex.Message}");
            throw;
        }
    }

    private async Task<TranscriptResult> WaitForRunCompletion(string runId, string videoUrl)
    {
        const int maxAttempts = 30;
        const int delaySeconds = 5; // Completion tests - 8 to 20 seconds

        for (int attempt = 0; attempt < maxAttempts; attempt++)
        {
            try
            {
                // Check the run status
                var statusUrl = $"https://api.apify.com/v2/actor-runs/{runId}";
                var statusResponse = await _httpClient.GetAsync(statusUrl);

                if (!statusResponse.IsSuccessStatusCode)
                {
                    _logger.LogWarning($"Failed to get run status: {statusResponse.StatusCode}");
                    await Task.Delay(TimeSpan.FromSeconds(delaySeconds));
                    continue;
                }

                var statusContent = await statusResponse.Content.ReadAsStringAsync();
                var statusData = JsonConvert.DeserializeObject<ApifyRunStatusResponse>(statusContent);

                _logger.LogInformation($"Run status: {statusData?.Data?.Status}, Attempt: {attempt + 1}/{maxAttempts}");

                if (statusData?.Data?.Status == "SUCCEEDED")
                {
                    // Run completed successfully, get the dataset items
                    return await GetRunResults(runId, videoUrl);
                }
                else if (statusData?.Data?.Status == "FAILED" || statusData?.Data?.Status == "ABORTED")
                {
                    _logger.LogWarning($"Apify run failed with status: {statusData?.Data?.Status}");
                    return null;
                }

                // Still running, wait and try again
                await Task.Delay(TimeSpan.FromSeconds(delaySeconds));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"Error checking run status: {ex.Message}");
                await Task.Delay(TimeSpan.FromSeconds(delaySeconds));
            }
        }

        _logger.LogWarning($"Timed out waiting for Apify run to complete after {maxAttempts} attempts");
        return null;
    }

    private async Task<TranscriptResult> GetRunResults(string runId, string videoUrl)
    {
        try
        {
            // Get dataset items
            var datasetUrl = $"https://api.apify.com/v2/actor-runs/{runId}/dataset/items";
            var datasetResponse = await _httpClient.GetAsync(datasetUrl);

            if (!datasetResponse.IsSuccessStatusCode)
            {
                _logger.LogWarning($"Failed to get dataset items: {datasetResponse.StatusCode}");
                return null;
            }

            var responseContent = await datasetResponse.Content.ReadAsStringAsync();
            var scraperResponse = JsonConvert.DeserializeObject<List<ApifyScraperResponse>>(responseContent);

            if (scraperResponse == null || !scraperResponse.Any())
            {
                _logger.LogWarning($"No data returned from Apify for video URL: {videoUrl}");
                return null;
            }

            var videoData = scraperResponse[0];

            // Map the response to our domain model (same as before)
            var result = new TranscriptResult
            {
                VideoId = videoData.Id,
                Title = videoData.Title,
                ChannelId = videoData.ChannelId,
                ChannelName = videoData.ChannelName,
                ChannelUrl = videoData.ChannelUrl,
                SubscriberCount = videoData.NumberOfSubscribers,
                ViewCount = videoData.ViewCount,
                LikeCount = videoData.Likes,
                CommentCount = videoData.CommentsCount,
                Duration = videoData.Duration,
                PublishedAt = videoData.Date,
                Description = videoData.Text,
                Subtitles = GetSubtitleContent(videoData.Subtitles)
            };

            _logger.LogInformation($"Successfully scraped video: {videoUrl}");
            return result;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, $"Error getting run results: {ex.Message}");
            return null;
        }
    }

    private string GetSubtitleContent(List<ApifySubtitle> subtitles)
    {
        if (subtitles == null || !subtitles.Any())
            return null;

        // Prefer auto-generated English subtitles
        var subtitle = subtitles.FirstOrDefault(s => s.Language == "en" && s.Type == "auto_generated")
                     ?? subtitles.FirstOrDefault();

        // Canvert SRT into a simpler format for easier reading
        var simpleSubtitles = Utilities.SrtConverter.ConvertSrtToSimpleFormat(subtitle?.Srt);

        return simpleSubtitles;
    }
}

// Classes only used by Transcript Service

public class ApifyRunResponse
{
    public ApifyRunData Data { get; set; }
}

public class ApifyRunData
{
    public string Id { get; set; }
    public string ActId { get; set; }
    public string ActorId { get; set; }
}

public class ApifyRunStatusResponse
{
    public ApifyRunStatusData Data { get; set; }
}

public class ApifyRunStatusData
{
    public string Id { get; set; }
    public string Status { get; set; }
}

public class ApifyScraperResponse
{
    public string Id { get; set; }
    public string Title { get; set; }
    public string Url { get; set; }
    public string ThumbnailUrl { get; set; }
    public int ViewCount { get; set; }
    public DateTime Date { get; set; }
    public int Likes { get; set; }
    public string ChannelName { get; set; }
    public string ChannelUrl { get; set; }
    public string ChannelId { get; set; }
    public long NumberOfSubscribers { get; set; }
    public string Duration { get; set; }
    public int CommentsCount { get; set; }
    public string Text { get; set; }
    public List<ApifySubtitle> Subtitles { get; set; }
}

public class ApifySubtitle
{
    public string SrtUrl { get; set; }
    public string Type { get; set; }
    public string Language { get; set; }
    public string Srt { get; set; }
}